#config_mirrorapi2.yml

api_key: "EMPTY"
#api_base: "http://127.0.0.1:12345/v1"
api_base: "http://127.0.0.1:12346/v1"
temperature: 0.1
#tools_folder: "/root/gzc/StableToolBench/toolenv2404_filtered"
tools_folder: "/home/t653z659/StableToolBench/toolenv/toolenv2404_filtered"
#port: 12001
port: 12002
#model: simulation-250123-qwen25-mixed
model: "mirrorapi"   # 这里跟上面保持一致

cache_folder: ./tool_response_cache #加一行cache看看会不会加速？